//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_online
    {
        public long aid { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> login_ts { get; set; }
        public Nullable<System.DateTime> last_ts { get; set; }
    
        public virtual admin admin { get; set; }
    }
}
