//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_permissions
    {
        public long aid { get; set; }
        public Nullable<int> modules { get; set; }
        public Nullable<int> merchant { get; set; }
        public long bank { get; set; }
        public int permit_flag { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual bank bank1 { get; set; }
        public virtual merchant merchant1 { get; set; }
    }
}
