//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bank()
        {
            this.admin_permissions = new HashSet<admin_permissions>();
            this.bank_bonus = new HashSet<bank_bonus>();
        }
    
        public long id { get; set; }
        public Nullable<long> min_limit { get; set; }
        public Nullable<long> max_limit { get; set; }
        public Nullable<System.DateTime> add_ts { get; set; }
        public string name { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<long> merchant_id { get; set; }
        public Nullable<long> terminal_id { get; set; }
        public Nullable<int> port { get; set; }
        public Nullable<long> month_limit { get; set; }
        public string offer_link { get; set; }
        public int status { get; set; }
        public string bin_code { get; set; }
        public Nullable<long> icon_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_permissions> admin_permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bank_bonus> bank_bonus { get; set; }
        public virtual icon icon { get; set; }
    }
}
