//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public long bill_id { get; set; }
        public decimal deposit { get; set; }
        public long uid { get; set; }
    
        public virtual user user { get; set; }
    }
}
