//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class card_monitoring
    {
        public long id { get; set; }
        public long card_id { get; set; }
        public Nullable<long> uid { get; set; }
        public string pan { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<long> amount { get; set; }
        public Nullable<bool> reversal { get; set; }
        public Nullable<bool> credit { get; set; }
        public long refnum { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> rad_pid { get; set; }
        public Nullable<long> rad_tid { get; set; }
        public string merchant_name { get; set; }
        public string epos_merchant_id { get; set; }
        public string epos_terminal_id { get; set; }
        public string street { get; set; }
        public string city { get; set; }
    
        public virtual card card { get; set; }
        public virtual user user { get; set; }
    }
}
