//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public card()
        {
            this.card_monitoring = new HashSet<card_monitoring>();
            this.card_monitoring_cabinet = new HashSet<card_monitoring_cabinet>();
            this.card_monitoring_load = new HashSet<card_monitoring_load>();
            this.periodic_bill = new HashSet<periodic_bill>();
            this.purchases = new HashSet<purchase>();
            this.top_up_transactions = new HashSet<top_up_transactions>();
        }
    
        public long card_id { get; set; }
        public string number { get; set; }
        public string expire { get; set; }
        public Nullable<long> uid { get; set; }
        public Nullable<int> is_primary { get; set; }
        public string name { get; set; }
        public Nullable<int> tpl { get; set; }
        public Nullable<long> tr_limit { get; set; }
        public Nullable<int> block { get; set; }
        public Nullable<int> user_block { get; set; }
        public string pc_token { get; set; }
        public string owner { get; set; }
        public Nullable<int> foreign_card { get; set; }
        public string owner_phone { get; set; }
        public long daily_limit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<card_monitoring> card_monitoring { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<card_monitoring_cabinet> card_monitoring_cabinet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<card_monitoring_load> card_monitoring_load { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<periodic_bill> periodic_bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase> purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<top_up_transactions> top_up_transactions { get; set; }
    }
}
