//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class card_bonus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public card_bonus()
        {
            this.user_bonus = new HashSet<user_bonus>();
        }
    
        public long card_id { get; set; }
        public string number { get; set; }
        public string expire { get; set; }
        public Nullable<long> xid { get; set; }
        public string name { get; set; }
        public Nullable<int> tpl { get; set; }
        public string pc_token { get; set; }
        public string owner { get; set; }
        public string password { get; set; }
        public Nullable<long> balance { get; set; }
        public Nullable<System.DateTime> notify_ts { get; set; }
        public string owner_phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_bonus> user_bonus { get; set; }
    }
}
