//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public long id { get; set; }
        public Nullable<double> usd_uzs { get; set; }
        public Nullable<double> usd_rub { get; set; }
        public Nullable<double> usd_eur { get; set; }
        public Nullable<System.DateTime> upd_ts { get; set; }
        public Nullable<System.DateTime> expiry_ts { get; set; }
        public int type { get; set; }
    }
}
