//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class error_codes
    {
        public long id { get; set; }
        public Nullable<int> value { get; set; }
        public string message_eng { get; set; }
        public string message_rus { get; set; }
        public string message_uzb { get; set; }
        public Nullable<int> ex_id { get; set; }
    }
}
