//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite
    {
        public int id { get; set; }
        public Nullable<long> uid { get; set; }
        public Nullable<int> field_id { get; set; }
        public Nullable<int> key { get; set; }
        public string value { get; set; }
        public string prefix { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public string name { get; set; }
        public Nullable<int> fav_id { get; set; }
    
        public virtual merchant merchant { get; set; }
        public virtual user user { get; set; }
    }
}
