//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public icon()
        {
            this.banks = new HashSet<bank>();
            this.merchant_group = new HashSet<merchant_group>();
            this.merchants = new HashSet<merchant>();
            this.top_up_merchants = new HashSet<top_up_merchants>();
        }
    
        public long id { get; set; }
        public string location { get; set; }
        public string path_hash { get; set; }
        public Nullable<int> kind { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<long> size { get; set; }
        public string sha1_sum { get; set; }
        public Nullable<int> b { get; set; }
        public Nullable<int> c { get; set; }
        public Nullable<int> d { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bank> banks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merchant_group> merchant_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merchant> merchants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<top_up_merchants> top_up_merchants { get; set; }
    }
}
