//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public long id { get; set; }
        public Nullable<int> aid { get; set; }
        public Nullable<System.DateTime> add_ts { get; set; }
        public string action { get; set; }
    }
}
