//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchant_access_info
    {
        public int merchant_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string api_json { get; set; }
        public string url { get; set; }
    
        public virtual merchant merchant { get; set; }
    }
}
