//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public merchant()
        {
            this.favorites = new HashSet<favorite>();
            this.admin_permissions = new HashSet<admin_permissions>();
            this.merchant_bonus = new HashSet<merchant_bonus>();
            this.merchant_fields = new HashSet<merchant_fields>();
            this.periodic_bill = new HashSet<periodic_bill>();
            this.purchases = new HashSet<purchase>();
            this.user_bills = new HashSet<user_bills>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> status { get; set; }
        public string inn { get; set; }
        public string contract { get; set; }
        public Nullable<System.DateTime> contract_date { get; set; }
        public string mfo { get; set; }
        public string ch_account { get; set; }
        public string merchant_id { get; set; }
        public string terminal_id { get; set; }
        public Nullable<int> port { get; set; }
        public Nullable<long> min_amount { get; set; }
        public Nullable<long> max_amount { get; set; }
        public int external { get; set; }
        public string ext_service_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public int rate { get; set; }
        public long rate_money { get; set; }
        public Nullable<int> position { get; set; }
        public int api_id { get; set; }
        public long icon_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorite> favorites { get; set; }
        public virtual icon icon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_permissions> admin_permissions { get; set; }
        public virtual merchant_access_info merchant_access_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merchant_bonus> merchant_bonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merchant_fields> merchant_fields { get; set; }
        public virtual merchant_api merchant_api { get; set; }
        public virtual merchant_qr_image merchant_qr_image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<periodic_bill> periodic_bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase> purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_bills> user_bills { get; set; }
    }
}
