//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchant_fields_data
    {
        public int id { get; set; }
        public Nullable<int> fid { get; set; }
        public Nullable<int> key { get; set; }
        public string value { get; set; }
        public string prefix { get; set; }
        public Nullable<int> extra_id { get; set; }
        public int parent_key { get; set; }
        public int service_id { get; set; }
        public int service_id_check { get; set; }
    
        public virtual merchant_fields merchant_fields { get; set; }
    }
}
