//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchant_fields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public merchant_fields()
        {
            this.merchant_fields_data = new HashSet<merchant_fields_data>();
        }
    
        public int fid { get; set; }
        public Nullable<int> mid { get; set; }
        public string label { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> input_digit { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<int> input_letter { get; set; }
        public string prefix_label { get; set; }
        public string label_uz1 { get; set; }
        public string label_uz2 { get; set; }
        public Nullable<int> min_length { get; set; }
        public Nullable<int> max_length { get; set; }
        public Nullable<int> parent_fid { get; set; }
        public string param_name { get; set; }
        public Nullable<int> usage { get; set; }
    
        public virtual merchant merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merchant_fields_data> merchant_fields_data { get; set; }
    }
}
