//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int id { get; set; }
        public string msg { get; set; }
        public Nullable<System.DateTime> add_ts { get; set; }
        public Nullable<int> send { get; set; }
        public Nullable<long> uid { get; set; }
        public string type { get; set; }
    
        public virtual user user { get; set; }
    }
}
