//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodic_bill
    {
        public long id { get; set; }
        public Nullable<long> uid { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public Nullable<int> field_id { get; set; }
        public Nullable<long> amount { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public string periodic_ts { get; set; }
        public string prefix { get; set; }
        public System.DateTime add_ts { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> last_bill_ts { get; set; }
        public Nullable<System.DateTime> last_notify_ts { get; set; }
        public long card_id { get; set; }
    
        public virtual card card { get; set; }
        public virtual merchant merchant { get; set; }
        public virtual user user { get; set; }
    }
}
