//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchases_reverse
    {
        public long id { get; set; }
        public Nullable<long> pid { get; set; }
        public Nullable<long> aid { get; set; }
        public Nullable<long> uid { get; set; }
        public string sms_code { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> ts_start { get; set; }
        public Nullable<System.DateTime> ts_confirm { get; set; }
        public string phone { get; set; }
        public string baz { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual purchase purchase { get; set; }
        public virtual user user { get; set; }
    }
}
