//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase()
        {
            this.purchase_info = new HashSet<purchase_info>();
            this.purchases_reverse = new HashSet<purchases_reverse>();
        }
    
        public long id { get; set; }
        public int merchant_id { get; set; }
        public string login { get; set; }
        public Nullable<long> amount { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<long> uid { get; set; }
        public string transaction_id { get; set; }
        public string pan { get; set; }
        public Nullable<int> status { get; set; }
        public string paynet_tr_id { get; set; }
        public int paynet_status { get; set; }
        public Nullable<long> receipt { get; set; }
        public long rad_paynet_tr_id { get; set; }
        public Nullable<long> rad_tr_id { get; set; }
        public Nullable<long> card_id { get; set; }
        public Nullable<long> bearn { get; set; }
        public long commission { get; set; }
        public string merch_rsp { get; set; }
    
        public virtual card card { get; set; }
        public virtual merchant merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_info> purchase_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchases_reverse> purchases_reverse { get; set; }
        public virtual user user { get; set; }
    }
}
