//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_info
    {
        public long rad_tr_id { get; set; }
        public long trn_id { get; set; }
        public string json_text { get; set; }
        public Nullable<long> request_type { get; set; }
        public string input_of_request { get; set; }
    
        public virtual purchase purchase { get; set; }
    }
}
