//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RAD_PAYEntities : DbContext
    {
        public RAD_PAYEntities()
            : base("name=RAD_PAYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activate_code> activate_code { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<bank> banks { get; set; }
        public virtual DbSet<bank_bonus> bank_bonus { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<card_bonus> card_bonus { get; set; }
        public virtual DbSet<card_monitoring> card_monitoring { get; set; }
        public virtual DbSet<card_monitoring_cabinet> card_monitoring_cabinet { get; set; }
        public virtual DbSet<card_monitoring_load> card_monitoring_load { get; set; }
        public virtual DbSet<card_monitoring_tarif> card_monitoring_tarif { get; set; }
        public virtual DbSet<card_topup_master> card_topup_master { get; set; }
        public virtual DbSet<card> cards { get; set; }
        public virtual DbSet<currency> currencies { get; set; }
        public virtual DbSet<epos> epos { get; set; }
        public virtual DbSet<error_codes> error_codes { get; set; }
        public virtual DbSet<fault> faults { get; set; }
        public virtual DbSet<favorite> favorites { get; set; }
        public virtual DbSet<icon> icons { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<merchant> merchants { get; set; }
        public virtual DbSet<merchant_api> merchant_api { get; set; }
        public virtual DbSet<merchant_bonus> merchant_bonus { get; set; }
        public virtual DbSet<merchant_fields> merchant_fields { get; set; }
        public virtual DbSet<merchant_fields_data> merchant_fields_data { get; set; }
        public virtual DbSet<merchant_group> merchant_group { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<paynet_info> paynet_info { get; set; }
        public virtual DbSet<periodic_bill> periodic_bill { get; set; }
        public virtual DbSet<purchase_info> purchase_info { get; set; }
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<purchases_reverse> purchases_reverse { get; set; }
        public virtual DbSet<rad_app_info> rad_app_info { get; set; }
        public virtual DbSet<sms_info> sms_info { get; set; }
        public virtual DbSet<temp_transaction> temp_transaction { get; set; }
        public virtual DbSet<top_up_merchants> top_up_merchants { get; set; }
        public virtual DbSet<top_up_transactions> top_up_transactions { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<user_bills> user_bills { get; set; }
        public virtual DbSet<user_bonus> user_bonus { get; set; }
        public virtual DbSet<user_devices> user_devices { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_cabinet> users_cabinet { get; set; }
        public virtual DbSet<users_full_registers> users_full_registers { get; set; }
        public virtual DbSet<admin_online> admin_online { get; set; }
        public virtual DbSet<admin_permissions> admin_permissions { get; set; }
        public virtual DbSet<merchant_access_info> merchant_access_info { get; set; }
        public virtual DbSet<merchant_qr_image> merchant_qr_image { get; set; }
        public virtual DbSet<qr_image> qr_image { get; set; }
        public virtual DbSet<users_online> users_online { get; set; }
    }
}
