//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_transaction
    {
        public long id { get; set; }
        public Nullable<long> uid { get; set; }
        public Nullable<long> dst_uid { get; set; }
        public long amount { get; set; }
        public System.DateTime create_ts { get; set; }
        public string token { get; set; }
        public string dstcard { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
