//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class top_up_merchants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public top_up_merchants()
        {
            this.top_up_transactions = new HashSet<top_up_transactions>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> option { get; set; }
        public Nullable<long> min_amount { get; set; }
        public Nullable<long> max_amount { get; set; }
        public Nullable<long> rate { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<long> card_id { get; set; }
        public Nullable<long> icon_id { get; set; }
    
        public virtual icon icon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<top_up_transactions> top_up_transactions { get; set; }
    }
}
