//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_cabinet
    {
        public long id { get; set; }
        public long uid { get; set; }
        public string password { get; set; }
        public Nullable<int> checkpassword { get; set; }
        public Nullable<System.DateTime> last_passwd_check { get; set; }
        public Nullable<int> check_count { get; set; }
        public Nullable<System.DateTime> checkcode_expiry { get; set; }
    
        public virtual user user { get; set; }
    }
}
