//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_full_registers
    {
        public long id { get; set; }
        public Nullable<long> uid { get; set; }
        public string fio { get; set; }
        public string passport_number { get; set; }
        public Nullable<System.DateTime> passport_start_date { get; set; }
        public Nullable<System.DateTime> passport_end_date { get; set; }
        public string passport_image_path { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string nationality { get; set; }
        public string citizenship { get; set; }
        public Nullable<int> status { get; set; }
        public string passport_serial { get; set; }
        public Nullable<int> level { get; set; }
    
        public virtual user user { get; set; }
    }
}
