//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_devices()
        {
            this.users_online = new HashSet<users_online>();
        }
    
        public long dev_id { get; set; }
        public Nullable<long> uid { get; set; }
        public string dev_token { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> add_ts { get; set; }
        public string notify_token { get; set; }
        public string os { get; set; }
        public Nullable<System.DateTime> login_ts { get; set; }
        public string dev_imei { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users_online> users_online { get; set; }
    }
}
