//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_bonus
    {
        public long id { get; set; }
        public long uid { get; set; }
        public Nullable<long> balance { get; set; }
        public Nullable<long> earns { get; set; }
        public Nullable<int> block { get; set; }
        public string fio { get; set; }
        public string pan { get; set; }
        public string expire { get; set; }
        public Nullable<System.DateTime> add_ts { get; set; }
        public Nullable<long> bonus_card_id { get; set; }
    
        public virtual card_bonus card_bonus { get; set; }
        public virtual user user { get; set; }
    }
}
