//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_bills
    {
        public long id { get; set; }
        public Nullable<long> uid { get; set; }
        public Nullable<long> uid2 { get; set; }
        public Nullable<long> amount { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public string value { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> add_ts { get; set; }
        public string comment { get; set; }
    
        public virtual merchant merchant { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
