//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_online
    {
        public long uid { get; set; }
        public string token { get; set; }
        public System.DateTime login_time { get; set; }
        public System.DateTime last_online { get; set; }
        public Nullable<long> dev_id { get; set; }
    
        public virtual user_devices user_devices { get; set; }
        public virtual user user { get; set; }
    }
}
